//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TimelogSoap")]
    public interface TimelogSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastTwoDaysProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLastTwoDaysProjectInfo(string empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFixedBidproject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFixedBidproject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBillableProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetBillableProjects(string pEmp_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNonBillableProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetNonBillableProjects(string pEmp_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetProfiles(int pProj_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkNotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddWorkNotes(string pEmp_id, int pProj_id, string pProf_id, decimal pOnline, decimal pOffline, decimal pFixed, string pWorkNotes, string pComments, System.DateTime pETA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkNotesByLogId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateWorkNotesByLogId(int pLogId, string pEmp_id, decimal pOnline, decimal pOffline, decimal pFixed, string pWorkNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkNotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllWorkNotes(string pEmp_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GoToAMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GoToAMS(string pEmp_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAmsLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowAmsLink(string pEmp_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllowDisallowPmLogout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AllowDisallowPmLogout(string empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSummaryReportForBB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSummaryReportForBB(string empId, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimelogSoapChannel : BAL.ServiceReference1.TimelogSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimelogSoapClient : System.ServiceModel.ClientBase<BAL.ServiceReference1.TimelogSoap>, BAL.ServiceReference1.TimelogSoap {
        
        public TimelogSoapClient() {
        }
        
        public TimelogSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimelogSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimelogSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimelogSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetLastTwoDaysProjectInfo(string empid) {
            return base.Channel.GetLastTwoDaysProjectInfo(empid);
        }
        
        public System.Xml.XmlNode GetFixedBidproject() {
            return base.Channel.GetFixedBidproject();
        }
        
        public System.Xml.XmlNode GetBillableProjects(string pEmp_id) {
            return base.Channel.GetBillableProjects(pEmp_id);
        }
        
        public System.Xml.XmlNode GetNonBillableProjects(string pEmp_id) {
            return base.Channel.GetNonBillableProjects(pEmp_id);
        }
        
        public System.Xml.XmlNode GetProfiles(int pProj_id) {
            return base.Channel.GetProfiles(pProj_id);
        }
        
        public System.Xml.XmlNode AddWorkNotes(string pEmp_id, int pProj_id, string pProf_id, decimal pOnline, decimal pOffline, decimal pFixed, string pWorkNotes, string pComments, System.DateTime pETA) {
            return base.Channel.AddWorkNotes(pEmp_id, pProj_id, pProf_id, pOnline, pOffline, pFixed, pWorkNotes, pComments, pETA);
        }
        
        public System.Xml.XmlNode UpdateWorkNotesByLogId(int pLogId, string pEmp_id, decimal pOnline, decimal pOffline, decimal pFixed, string pWorkNotes) {
            return base.Channel.UpdateWorkNotesByLogId(pLogId, pEmp_id, pOnline, pOffline, pFixed, pWorkNotes);
        }
        
        public System.Xml.XmlNode GetAllWorkNotes(string pEmp_id) {
            return base.Channel.GetAllWorkNotes(pEmp_id);
        }
        
        public string GoToAMS(string pEmp_id) {
            return base.Channel.GoToAMS(pEmp_id);
        }
        
        public string ShowAmsLink(string pEmp_id) {
            return base.Channel.ShowAmsLink(pEmp_id);
        }
        
        public string AllowDisallowPmLogout(string empId) {
            return base.Channel.AllowDisallowPmLogout(empId);
        }
        
        public string GetSummaryReportForBB(string empId, string pass) {
            return base.Channel.GetSummaryReportForBB(empId, pass);
        }
    }
}
