//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptAnnouncement
    {
        public int ID { get; set; }
        public Nullable<int> fkAnnouncement { get; set; }
        public Nullable<int> fkEmp { get; set; }
        public Nullable<System.DateTime> AcceptDateTime { get; set; }
    
        public virtual AcceptAnnouncement AcceptAnnouncement1 { get; set; }
        public virtual AcceptAnnouncement AcceptAnnouncement2 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Announcement Announcement { get; set; }
    }
}
