//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Announcement()
        {
            this.AcceptAnnouncements = new HashSet<AcceptAnnouncement>();
        }
    
        public int ID { get; set; }
        public string AnnouncementContent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AnnouncementDate { get; set; }
    
        public virtual ICollection<AcceptAnnouncement> AcceptAnnouncements { get; set; }
    }
}
