//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalCycle
    {
        public int ID { get; set; }
        public Nullable<int> Join_Month1 { get; set; }
        public Nullable<int> Join_Month2 { get; set; }
        public Nullable<int> Join_Month3 { get; set; }
        public Nullable<int> Next_Appraisal_Month { get; set; }
    }
}
