//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentCriteria
    {
        public AssessmentCriteria()
        {
            this.PerformanceEvaluations = new HashSet<PerformanceEvaluation>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> fkGrade { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> fkAssessmentRevision { get; set; }
    
        public virtual ICollection<PerformanceEvaluation> PerformanceEvaluations { get; set; }
        public virtual AssessmentRevision AssessmentRevision { get; set; }
        public virtual tbl_E_Grade tbl_E_Grade { get; set; }
    }
}
