//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpCertification
    {
        public int ID { get; set; }
        public Nullable<int> fkEmployee { get; set; }
        public Nullable<int> fkCertification { get; set; }
        public string Institution { get; set; }
        public Nullable<int> PassingYear { get; set; }
        public Nullable<decimal> PercentSecured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tbl_E_Certification tbl_E_Certification { get; set; }
    }
}
