//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDependent
    {
        public int ID { get; set; }
        public Nullable<int> fkEmployee { get; set; }
        public string DependentName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DependentContactNo { get; set; }
        public string DependentAddress { get; set; }
        public Nullable<bool> IsNominee { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> fkRelationship { get; set; }
    
        public virtual tbl_E_Relationship tbl_E_Relationship { get; set; }
    }
}
