//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRole
    {
        public int ID { get; set; }
        public int fkRole { get; set; }
        public int fkEmployee { get; set; }
    
        public virtual tbl_E_Role tbl_E_Role { get; set; }
    }
}
