//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AcceptAnnouncements = new HashSet<AcceptAnnouncement>();
            this.tbl_EmployeeProbationDetails = new HashSet<tbl_EmployeeProbationDetails>();
            this.tbl_EmployeeProbationDetails1 = new HashSet<tbl_EmployeeProbationDetails>();
            this.tbActionTakens = new HashSet<tbActionTaken>();
            this.tbEmailQueues = new HashSet<tbEmailQueue>();
            this.tbEmployeeAppraisalRecords = new HashSet<tbEmployeeAppraisalRecord>();
            this.tbEmployeeBankAndPFRecords = new HashSet<tbEmployeeBankAndPFRecord>();
            this.tbEmployeeExitRecords = new HashSet<tbEmployeeExitRecord>();
            this.tbEmployeeRefrences = new HashSet<tbEmployeeRefrence>();
            this.tbEmployeeStatusRecords = new HashSet<tbEmployeeStatusRecord>();
            this.tbEmployeeAddresses = new HashSet<tbEmployeeAddress>();
        }
    
        public int ID { get; set; }
        public string Emp_Id { get; set; }
        public string Emp_Code { get; set; }
        public string LoginPassword { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> ReportingTo { get; set; }
        public Nullable<int> ProjectReportingTo { get; set; }
        public string EmergencyContact { get; set; }
        public string ExtNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string PresentAddress { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public string PermanentAddress { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> VisaExpiry { get; set; }
        public string SalAccNo { get; set; }
        public string PanNo { get; set; }
        public string HomePhone { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public string PersonalEmail { get; set; }
        public string OfficialEmail { get; set; }
        public string SkypeId { get; set; }
        public string YahooId { get; set; }
        public string MSNId { get; set; }
        public string GtalkId { get; set; }
        public string SparkId { get; set; }
        public string OutlookId { get; set; }
        public Nullable<int> fkEmpType { get; set; }
        public Nullable<int> fkDepartment { get; set; }
        public Nullable<int> fkDesignation { get; set; }
        public Nullable<int> fkEmpGrade { get; set; }
        public string EmpStatus { get; set; }
        public string ReferredBy { get; set; }
        public string HiringSource { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string ExitComment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AppraisalDueOn { get; set; }
        public Nullable<int> fkBloodGroup { get; set; }
        public Nullable<int> fkExitStatus { get; set; }
        public string RefName1 { get; set; }
        public string RefCompany1 { get; set; }
        public string RefDesignation1 { get; set; }
        public string RefEmail1 { get; set; }
        public string RefContactNo1 { get; set; }
        public string RefName2 { get; set; }
        public string RefCompany2 { get; set; }
        public string RefDesignation2 { get; set; }
        public string RefEmail2 { get; set; }
        public string RefContactNo2 { get; set; }
        public string RefName3 { get; set; }
        public string RefCompany3 { get; set; }
        public string RefDesignation3 { get; set; }
        public string RefEmail3 { get; set; }
        public string RefContactNo3 { get; set; }
        public Nullable<bool> IsAccessWorkdiary { get; set; }
        public string FullName { get; set; }
        public string MachineIpAddress { get; set; }
        public Nullable<System.DateTime> Confirmationdate { get; set; }
        public string DrivingLicienceNo { get; set; }
        public Nullable<int> fkEmploymentStatus { get; set; }
        public Nullable<bool> Organizationalemail { get; set; }
        public Nullable<bool> RelievingMail { get; set; }
        public string CardNumber { get; set; }
        public Nullable<decimal> RelevantExperience { get; set; }
        public Nullable<decimal> PriorExperience { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public string TrainingDuration { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string Userip { get; set; }
        public Nullable<int> CardNo { get; set; }
        public string TFMP { get; set; }
    
        public virtual ICollection<AcceptAnnouncement> AcceptAnnouncements { get; set; }
        public virtual ICollection<tbl_EmployeeProbationDetails> tbl_EmployeeProbationDetails { get; set; }
        public virtual ICollection<tbl_EmployeeProbationDetails> tbl_EmployeeProbationDetails1 { get; set; }
        public virtual tbl_E_Department tbl_E_Department { get; set; }
        public virtual tbl_E_EmploymentStatus tbl_E_EmploymentStatus { get; set; }
        public virtual tbl_E_Designation tbl_E_Designation { get; set; }
        public virtual ICollection<tbActionTaken> tbActionTakens { get; set; }
        public virtual ICollection<tbEmailQueue> tbEmailQueues { get; set; }
        public virtual ICollection<tbEmployeeAppraisalRecord> tbEmployeeAppraisalRecords { get; set; }
        public virtual ICollection<tbEmployeeBankAndPFRecord> tbEmployeeBankAndPFRecords { get; set; }
        public virtual ICollection<tbEmployeeExitRecord> tbEmployeeExitRecords { get; set; }
        public virtual ICollection<tbEmployeeRefrence> tbEmployeeRefrences { get; set; }
        public virtual ICollection<tbEmployeeStatusRecord> tbEmployeeStatusRecords { get; set; }
        public virtual ICollection<tbEmployeeAddress> tbEmployeeAddresses { get; set; }
        public virtual tbl_E_BloodGroup tbl_E_BloodGroup { get; set; }
        public virtual tbl_E_EmpType tbl_E_EmpType { get; set; }
        public virtual tbl_E_ExitStatus tbl_E_ExitStatus { get; set; }
        public virtual tbl_E_Grade tbl_E_Grade { get; set; }
    }
}
