//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTechnicalSkill
    {
        public int ID { get; set; }
        public Nullable<int> fkEmployee { get; set; }
        public Nullable<int> fkTechnicalSkill { get; set; }
        public string TotalExp { get; set; }
        public Nullable<int> ExpertiseLevel { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tbl_E_Technicalskills tbl_E_Technicalskills { get; set; }
    }
}
