//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavesQuota
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<int> fkLeaveType { get; set; }
        public Nullable<int> MaxLimit { get; set; }
    
        public virtual tbl_E_LeaveType tbl_E_LeaveType { get; set; }
    }
}
