//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_app_update_table
    {
        public int ID { get; set; }
        public string VersionNumber { get; set; }
        public string VersionFileLinkAndroid { get; set; }
        public string VersionFileLinkIOS { get; set; }
        public string VersionMessageText { get; set; }
        public string PreviousVersionFileLinkAndroid { get; set; }
        public string PreviousVersionFileLinkIOS { get; set; }
    }
}
