//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceAppraisal
    {
        public PerformanceAppraisal()
        {
            this.PerformanceEvaluations = new HashSet<PerformanceEvaluation>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string AppraisalComment { get; set; }
        public Nullable<System.DateTime> ReviewPeriodFrom { get; set; }
        public Nullable<System.DateTime> ReviewPeriodTo { get; set; }
        public Nullable<int> fkAppraisalRating { get; set; }
        public string EmployeeComment { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<int> fkEmployee { get; set; }
        public Nullable<int> CurrentCTC { get; set; }
        public Nullable<int> AppraisedCTC { get; set; }
        public Nullable<System.DateTime> NextAppraisalDueOn { get; set; }
    
        public virtual ICollection<PerformanceEvaluation> PerformanceEvaluations { get; set; }
        public virtual tbl_E_AppraisalRating tbl_E_AppraisalRating { get; set; }
    }
}
