//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderLeave
    {
        public int ID { get; set; }
        public string Guid { get; set; }
        public Nullable<int> fkLeavestatus { get; set; }
        public string LineManager { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
    
        public virtual LeaveStatu LeaveStatu { get; set; }
    }
}
