//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DocumentType
    {
        public tb_DocumentType()
        {
            this.EmpDocuments = new HashSet<EmpDocument>();
        }
    
        public int Id { get; set; }
        public string DocumentName { get; set; }
    
        public virtual ICollection<EmpDocument> EmpDocuments { get; set; }
    }
}
