//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActionTaken
    {
        public int ID { get; set; }
        public int ActionTakenBy { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual tbEmailQueue tbEmailQueue { get; set; }
    }
}
