//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmailFailureRecord
    {
        public int ID { get; set; }
        public int QueueID { get; set; }
        public string FailureRecords { get; set; }
    
        public virtual tbEmailQueue tbEmailQueue { get; set; }
    }
}
