//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmployeeExitRecord
    {
        public int ID { get; set; }
        public Nullable<int> FKEmployee { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<int> LeavingReason { get; set; }
        public string ReasonDetails { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> FinalSettlementDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<System.DateTime> ExitInterviewDate { get; set; }
        public Nullable<bool> IsNoticeRequired { get; set; }
        public Nullable<bool> IsNoticeServed { get; set; }
        public Nullable<int> ShortFallInNotice { get; set; }
        public Nullable<bool> IsDeceased { get; set; }
        public Nullable<System.DateTime> DemiseDate { get; set; }
        public Nullable<System.DateTime> RetireDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsRehired { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsReleavingMail { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual tbl_E_ExitStatus tbl_E_ExitStatus { get; set; }
    }
}
