//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmailQueue
    {
        public tbEmailQueue()
        {
            this.tbActionTakens = new HashSet<tbActionTaken>();
            this.tbEmailFailureRecords = new HashSet<tbEmailFailureRecord>();
        }
    
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int EventID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> EmailSentAt { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public System.DateTime PendingDate { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<tbActionTaken> tbActionTakens { get; set; }
        public virtual tbApplicationEvent tbApplicationEvent { get; set; }
        public virtual ICollection<tbEmailFailureRecord> tbEmailFailureRecords { get; set; }
    }
}
