//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmployeeBankAndPFRecord
    {
        public int ID { get; set; }
        public Nullable<int> FKEmployee { get; set; }
        public Nullable<int> FKBank { get; set; }
        public string Branch { get; set; }
        public string ISFCCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string PaymentType { get; set; }
        public string PayableAt { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsPFScheme { get; set; }
        public Nullable<System.DateTime> PFJoinDate { get; set; }
        public string PFScheme { get; set; }
        public string PFNumber { get; set; }
        public Nullable<bool> IsEPFExcessContribution { get; set; }
        public Nullable<bool> IsEPSExcessContribution { get; set; }
        public Nullable<bool> IsESIScheme { get; set; }
        public string ESINumber { get; set; }
        public string FamilyPFNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual tbl_E_Banks tbl_E_Banks { get; set; }
    }
}
