//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmployeeStatusRecord
    {
        public int ID { get; set; }
        public int FKEmployee { get; set; }
        public Nullable<int> FKGrade { get; set; }
        public Nullable<int> FKDesignation { get; set; }
        public Nullable<int> FKEmpType { get; set; }
        public Nullable<int> FKDepartment { get; set; }
        public Nullable<int> FKEmploymentStatus { get; set; }
        public string ExitStatus { get; set; }
        public Nullable<int> EventRecord { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual tbEmployeeStatusEvent tbEmployeeStatusEvent { get; set; }
        public virtual tbl_E_Designation tbl_E_Designation { get; set; }
        public virtual tbl_E_EmpType tbl_E_EmpType { get; set; }
        public virtual tbl_E_Grade tbl_E_Grade { get; set; }
        public virtual tbl_E_EmploymentStatus tbl_E_EmploymentStatus { get; set; }
    }
}
