//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_E_Department
    {
        public tbl_E_Department()
        {
            this.Employees = new HashSet<Employee>();
            this.tbEmployeeAppraisalRecords = new HashSet<tbEmployeeAppraisalRecord>();
        }
    
        public int ID { get; set; }
        public string DeptName { get; set; }
        public string DepartmentHead { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<tbEmployeeAppraisalRecord> tbEmployeeAppraisalRecords { get; set; }
    }
}
