//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_E_CalendarHoliday
    {
        public int ID { get; set; }
        public string OccasionName { get; set; }
        public Nullable<System.DateTime> OccasionDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    }
}
