//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllEmployeesLeaveDetails
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string EmpId { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public string Designation { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ConfirmationStatus { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string C25 { get; set; }
        public string C26 { get; set; }
        public string C27 { get; set; }
        public string C28 { get; set; }
        public string C29 { get; set; }
        public string C30 { get; set; }
        public string C31 { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public string C8 { get; set; }
        public string C9 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public Nullable<decimal> LeaveBalance_CL { get; set; }
        public Nullable<decimal> LeaveBalance_SL { get; set; }
        public Nullable<decimal> LeaveBalance_PL { get; set; }
        public Nullable<decimal> LeaveBalance_TL { get; set; }
        public Nullable<decimal> LeaveTaken_CL { get; set; }
        public Nullable<decimal> LeaveTaken_SL { get; set; }
        public Nullable<decimal> LeaveTaken_PL { get; set; }
        public Nullable<decimal> LeaveTaken_TL { get; set; }
        public Nullable<decimal> Leave_Balancefornexttenure_CL { get; set; }
        public Nullable<decimal> Leave_Balancefornexttenure_SL { get; set; }
        public Nullable<decimal> Leave_Balancefornexttenure_PL { get; set; }
        public Nullable<decimal> Leave_Balancefornexttenure_TL { get; set; }
        public Nullable<decimal> LWPLeave { get; set; }
        public Nullable<decimal> TotalDays { get; set; }
        public Nullable<decimal> PayableDays { get; set; }
    }
}
