//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccessCardEvents
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public Nullable<int> Modify { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EventCH { get; set; }
        public Nullable<int> DoorID { get; set; }
        public string DoorName { get; set; }
    }
}
