//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DI_Geo_States
    {
        public double State_Id { get; set; }
        public Nullable<double> fk_Country_Id { get; set; }
        public string State_Name { get; set; }
    }
}
