//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_E_LeaveType
    {
        public tbl_E_LeaveType()
        {
            this.DetailedLeaveStatus = new HashSet<DetailedLeaveStatu>();
            this.DetailedLeaveStatus1 = new HashSet<DetailedLeaveStatu>();
            this.LeavesQuotas = new HashSet<LeavesQuota>();
            this.LeaveStatus = new HashSet<LeaveStatu>();
            this.LeaveStatus1 = new HashSet<LeaveStatu>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual ICollection<DetailedLeaveStatu> DetailedLeaveStatus { get; set; }
        public virtual ICollection<DetailedLeaveStatu> DetailedLeaveStatus1 { get; set; }
        public virtual ICollection<LeavesQuota> LeavesQuotas { get; set; }
        public virtual ICollection<LeaveStatu> LeaveStatus { get; set; }
        public virtual ICollection<LeaveStatu> LeaveStatus1 { get; set; }
    }
}
