//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_E_Banks
    {
        public tbl_E_Banks()
        {
            this.tbEmployeeBankAndPFRecords = new HashSet<tbEmployeeBankAndPFRecord>();
        }
    
        public int ID { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<tbEmployeeBankAndPFRecord> tbEmployeeBankAndPFRecords { get; set; }
    }
}
