//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllEmployeesCustomLeaveReport
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string EmpId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TotalAllocatedLeaves { get; set; }
        public Nullable<decimal> TotalLeavesTaken { get; set; }
        public Nullable<decimal> CasualLeavesTaken { get; set; }
        public Nullable<decimal> SickLeavesTaken { get; set; }
        public Nullable<decimal> PaidLeavesTaken { get; set; }
        public Nullable<decimal> LWPTaken { get; set; }
    }
}
