//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_E_PolicyCategory
    {
        public tbl_E_PolicyCategory()
        {
            this.tbPolicies = new HashSet<tbPolicy>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tbl_E_PolicyCategory tbl_E_PolicyCategory1 { get; set; }
        public virtual tbl_E_PolicyCategory tbl_E_PolicyCategory2 { get; set; }
        public virtual ICollection<tbPolicy> tbPolicies { get; set; }
    }
}
