//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccessCardData
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> CardNo { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Dept { get; set; }
        public string Source { get; set; }
        public string Note { get; set; }
    }
}
