//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_E_Technicalskills
    {
        public tbl_E_Technicalskills()
        {
            this.EmpTechnicalSkills = new HashSet<EmpTechnicalSkill>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EmpTechnicalSkill> EmpTechnicalSkills { get; set; }
    }
}
