//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNoticePeriod
    {
        public int ID { get; set; }
        public int FkDesignation { get; set; }
        public int NoticePeriod { get; set; }
    
        public virtual tbl_E_Designation tbl_E_Designation { get; set; }
    }
}
