//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_Announcement
    {
        public TL_Announcement()
        {
            this.TL_AnnouncementAccept = new HashSet<TL_AnnouncementAccept>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Contents { get; set; }
    
        public virtual ICollection<TL_AnnouncementAccept> TL_AnnouncementAccept { get; set; }
    }
}
