//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_Ethics
    {
        public TL_Ethics()
        {
            this.TL_AcceptEthics = new HashSet<TL_AcceptEthics>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<TL_AcceptEthics> TL_AcceptEthics { get; set; }
    }
}
