//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_LateComing
    {
        public int id { get; set; }
        public string Emp_Id { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
