//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_TimeLog
    {
        public int ID { get; set; }
        public string TimeBreak { get; set; }
        public string fkEmp_id { get; set; }
        public Nullable<System.DateTime> Login { get; set; }
        public Nullable<System.DateTime> Logout { get; set; }
        public string WorkingHours { get; set; }
        public string ProductiveHours { get; set; }
        public string LoginIP { get; set; }
        public string LogoutIP { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string Earlycheckoutreson { get; set; }
        public string Userip { get; set; }
    }
}
